### PR TITLE
Upgrade Angular 8

### PR DESCRIPTION
**Pull request by sambaptista**
It was already working in angular 8 environment but with some peer dependencies unmatched. 

This fixes it and update dependencies.

### CODE REVIEW

**Comment by sambaptista** [comment]
Can you please publish on npm ?

**Comment by sambaptista** [comment]
Maybe you would be open minded to contributors and give access as well on repository and on the registry package ?

**Comment by danielpdev** [comment]
@sambaptista I am on holiday right now and can't update the npm package. You will get access to both repository and npm registry in two weeks. 

Thanks

**Comment by sambaptista** [comment]
Great. Enjoy your holidays :)

**Comment by sambaptista** [comment]
Thx for permissions. 

Do you use to do some non-scripted manipulations before release ?

**Comment by danielpdev** [comment]
@sambaptista No, I just use the regular commands like building for production and then publish using npm.

**Pull request merged**
