### PR TITLE
Upgrade to Angular 9 and animejs 3

### PR DESCRIPTION
**Pull request by PowerKiKi**
This also:

- upgrade all others deps to latest versions
- fixes unit and e2e tests that were broken for a while
- delete obsolete backup files
- disable Ivy because libs cannot be published as Ivy for now
- always use `npm` via `ng` commands

### CODE REVIEW

**Comment by PowerKiKi** [comment]
This is the proper, final version of Angular 9 migration PR.

**Comment by PowerKiKi** [comment]
The last commit adds Github Actions integration to run the tests and linting. You can see it is passing there: https://github.com/Ecodev/angular-particle-effect-button/actions/runs/47145011

**Comment by danielpdev** [comment]
You did a great job here!
Thanks for taking your time to fix tests and upgrade to this package to Angular 9.
I'll merge and push update npm version.

**Comment by PowerKiKi** [comment]
Thanks for merging and releasing promptly.

For the next version, I would suggest to release it as 1.0.0 to better communicate the fact that this package is 2 years, maintained and production ready.

**Pull request merged**
